### ISSUE TITLE
5/5 project

### ISSUE THREAD

**Issue by Sandile-Dev01** [amansgz/css-interactive-rating-component#1]
This project is awesome bud from the UI to the responsiveness but it’s missing one element which can boost the UX:

- A button/nav text to return to home after the final page (or on it)

**Comment by amansgz** [comment]
This is a challenge from Frontend Mentor:
https://www.frontendmentor.io/challenges/interactive-rating-component-koxpeBUmI

Thanks Sandile for your comments, I've just added a *rate again* button to thanks card.

**Comment by amansgz** [comment]
This is a challenge from Frontend Mentor:
https://www.frontendmentor.io/challenges/interactive-rating-component-koxpeBUmI

Thanks @Sandile-Dev01 for your comments, I've just added a rate again button to thanks card.

**Comment by Sandile-Dev01** [comment]
I saw it, it’s awesome bro. Nice feature🔥
